### ISSUE TITLE
site_wait_for_online local-exec displays API token

### ISSUE THREAD

**Issue by TJM** [cklewar/f5-xc-modules#481]
The API token should be treated as "sensitive" and not displayed in the TF output (logs).

> module.f5_ce.module.node[0].module.site_wait_for_online.null_resource.check_site_status (local-exec): Executing: ["/usr/bin/env" "bash" "-c" ".terraform/modules/f5_ce/f5xc/status/site/scripts/check.sh https://davita.console.ves.volterra.io/api/config/namespaces/system/sites/tjm-f5lab-f5xc-8d8a20?response_format=GET_RSP_FORMAT_DEFAULT O(CENSORED)ibB4I= da(CENSORED)gm"]

I am sure that the "API TOKEN" should not be exposed. I am not sure whether the tenant ID is "private" as well.

**Comment by cklewar** [comment]
Two options:

- Set API token input variable or any other variable which should be masked in output attribute `sensitive=true`.
- Introduced `is_sensitive`. By setting this `api_token` and `tenant` will be masked
````hlc
module "gcp_ce" {
  source                         = "./modules/f5xc/ce/gcp"
  is_sensitive                   = true
  gcp_region                     = var.gcp_region
  machine_type                   = var.machine_type
  network_name                   = module.vpc.network_name
  ssh_username                   = "centos"
............
````

**Comment by TJM** [comment]
I think that the "`sensitive = true`" should be set on the API Key variable (in the variables.tf files) and possibly tenant ID (still not sure if that is a "private" thing). I don't think you want to make the whole module sensitive, as that makes it more difficult to troubleshoot.

**Comment by TJM** [comment]
```
module.f5_ce_multi.module.node[0].module.site_wait_for_online.null_resource.check_site_status (local-exec): (output suppressed due to sensitive value in config)
```

OK, so that is less than useful as well... while it does suppress the API Key from the output, it doesn't do so selectively. I think we should modify the script to not show it in the first place instead?

**Comment by cklewar** [comment]
Removed API token from output on script level.
